spring.application.name=bakene-concierge-backen

spring.datasource.url=jdbc:postgresql://ep-broad-forest-axtaxq8k-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_gDQxN9sY2VRy

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

whatsapp.verify.token=bakene123
whatsapp.phone.number.id=1294674903721397
whatsapp.access.token=EAAWgL5KV4ngBSHBNc9CkMFnlAOOhGoXWQ04Es2xX2tsA8VzJUdgK5YsM741Ym0QFYon6ZA0Tag3C0cpDy3uXdvXYEYIE2Hob9ssLBaqiZBAzu5eTVZBZBoQYwCMrypWqtqkMlV8h0ByqGBeJGwoBxYhc5lxdy3FyYkpwlCfKTnIM332a7uv7lqzGgCFPUwWFTfQCuX7faQpZBfmLzV0pdrzByJRpAuDVoSFweqRhTf9sXlhdVyMyJAhZCscyhtQ80yMXbfputdjyJ89k12bcDPZBzfC

server.port=8080